version: '3'

services:
  backend:
    image: codingpoetss/bupt-navigation:latest
    container_name: bupt-navigation-backend
    build: .
    command: sh -c "bash initial.sh"
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - map-navigation-network


  db:
    image: postgres:13
    container_name: bupt-navigation-postgres
#    ports:
#      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - map-navigation-network

volumes:
  postgres_data:


networks:
  map-navigation-network:
    name: map-navigation-network
    driver: bridge
